### ISSUE TITLE
Update project to Phoenix 1.4

### ISSUE THREAD

**Issue by SimonLab** [dwyl/phoenix-ecto-encryption-example#15]
- [x] Go over the steps and make sure everything is up to date and working with Phoenix 1.4

linked to 
- https://github.com/dwyl/learn-phoenix-framework/issues/118#issue-378671819 
- https://gist.github.com/chrismccord/bb1f8b136f5a9e4abc0bfc07b832257e

**Comment by SimonLab** [comment]
done with #16

**Comment by nelsonic** [comment]
Thanks @SimonLab 🥇
