### ISSUE TITLE
best practices around changeset

### ISSUE THREAD

**Issue by tiotolstoy** [dwyl/phoenix-ecto-encryption-example#29]
Hello, for my use case, I needed to encrypt the changes in the changeset. 
Is it OK that if instead of `changeset.data.email`, I use `changeset.changes.email`? Is that a best practice.
PS. not using it for email, using for another sensitive field.
```
{:ok, encrypted_email} = EncryptedField.dump(changeset.data.email)
{:ok, encrypted_name} = EncryptedField.dump(changeset.data.name)
```

**Comment by nelsonic** [comment]
@tiotolstoy good question, thanks for opening it. 👍 
If you are receiving data from a Form, then it makes sense to use `changeset.changes.email` to access the whichever field that needs to be encrypted.

**Comment by tiotolstoy** [comment]
That's exactly what I was using it for, thanks @nelsonic!
