### ISSUE TITLE
embed_as not implemented

### ISSUE THREAD

**Issue by fivetwentysix** [dwyl/phoenix-ecto-encryption-example#31]
Seems that Ecto.Type wants us to implement this...

`function embed_as/1 required by behaviour Ecto.Type is not implemented (in module Encryption.PasswordField)`

**Comment by nelsonic** [comment]
@fivetwentysix thanks for opening this issue. 👍 
Indeed with Ecto 3.0 there are new callback functions that need to be included.
We recently added these to **`Fields`**: https://github.com/dwyl/fields/pull/63/files#r386020478
The code is quite simple:
```elixir
  def embed_as(_), do: :self

  def equal?(term1, term2), do: term1 == term2
```

We need to update the `README.md` in this example with these functions. 💭

**Comment by nelsonic** [comment]
Added with tests via: #47
