### ISSUE TITLE
broken hitcount

### ISSUE THREAD

**Issue by Arhell** [dwyl/phoenix-ecto-encryption-example#40]
![phoenix-encryption-example-hits-badge-broken](https://user-images.githubusercontent.com/194400/162315581-697b5015-d56b-4cfa-b31d-d15365c84c72.png)

**Comment by nelsonic** [comment]
I'd totally forgotten this repo! It has 200+ stars! Obvs it's been useful to several people. Thanks for reminding me. 🙌

**Comment by nelsonic** [comment]
Fixed in #41 ✅ 
Thanks again @Arhell
